# Generated by Django 3.0.8 on 2021-08-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210727_1559'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartproduct',
            table='cartproduct',
        ),
    ]
